version: "3.8"
networks:
  test:

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/vscode/app
    tty: true
    networks:
      - test

  db:
    image: postgres:15.3-alpine
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=root
    ports:
      - "6500:5432"
    networks:
      - test
