version: '3.8'
services:
  db_container:
    restart: always
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"